package com.samsung.genuicraft.sdk

import android.content.Context
import com.google.gson.JsonParser
import java.security.MessageDigest
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ensureActive
import kotlinx.coroutines.withContext
import kotlin.coroutines.coroutineContext

/**
 * Direct response-to-Express inference for the trained E2B v10 checkpoint.
 *
 * Uses the frozen training scaffold (system + user/model example + raw response),
 * without model repair turns. Generated output first crosses strict compilation, then bounded
 * structural repair. If neither preserves the supplied response, the SDK returns a deterministic
 * source-bound A2UI layout and records that fallback in the success warnings.
 */
class GenUiTrainedConverter internal constructor(
    private val provider: GenUiProvider,
    private val contract: TrainedPromptContract,
) {
    constructor(context: Context, provider: GenUiProvider) : this(
        provider,
        TrainedPromptContract.parse(context.applicationContext.assets.open(PROMPT_ASSET)
            .bufferedReader(Charsets.UTF_8).use { it.readText() }),
    )

    suspend fun convert(request: GenUiRequest): GenUiConversionResult = withContext(Dispatchers.Default) {
        val start = System.nanoTime()
        fun elapsed() = (System.nanoTime() - start) / 1_000_000
        coroutineContext.ensureActive()
        val problem = if (request.text.isBlank()) "Input text is empty."
            else GenUiConverter.requestProblem(request)
        if (problem != null) return@withContext GenUiConversionResult.Failure(problem, provider.id, elapsed(), 0)
        var raw: String? = null
        try {
            val output = provider.generate(contract.prompt(request.text))
            raw = output.text.trim()
            coroutineContext.ensureActive()
            val compiled = GenUiCompiler.compileWithRepair(raw, request.text)
            val document = SourceAttribution.append(compiled.document, request.sources)
                .copy(profile = PROFILE)
            GenUiConversionResult.Success(
                document = document,
                provider = provider.id,
                elapsedMs = elapsed(),
                attempts = 1,
                warnings = buildList {
                    add("Runtime: ${output.runtime}")
                    when (compiled.repairKind) {
                        GenUiRepairKind.NONE -> add("Trained E2B output passed strict compilation and mechanical source-integrity checks.")
                        GenUiRepairKind.STRUCTURAL -> add("Trained E2B output passed bounded syntax repair and mechanical source-integrity checks.")
                        GenUiRepairKind.SOURCE_TEXT_FALLBACK -> add("Trained E2B output was rejected; built deterministic typed A2UI from exact source blocks.")
                    }
                    addAll(compiled.diagnostics)
                },
                repairKind = compiled.repairKind,
            )
        } catch (cancelled: CancellationException) {
            throw cancelled
        } catch (failure: Exception) {
            GenUiConversionResult.Failure(failure.message ?: failure.javaClass.simpleName,
                provider.id, elapsed(), 1, raw)
        }
    }

    companion object {
        const val PROFILE = "trained_e2b_v10_w4"
        const val PROMPT_ASSET = "genuicraft/prompts/e2b_v10_shared_prompt.json"
        const val CONTRACT_SHA256 = "005ef700eee29a4429c895ac6c86580003c43d0ad35e67cbb92a9d4cf0e8c1d2"
    }
}

/** Pinned snapshot generated by training.data.shared_prompt; never substitute a shorter prompt. */
internal data class TrainedPromptContract(
    val system: String,
    val example: List<GenUiPromptMessage>,
    val taskPrefix: String,
) {
    fun prompt(response: String): GenUiPrompt = GenUiPrompt(
        system = system,
        user = taskPrefix + response.trim(),
        maxOutputTokens = 2048,
        temperature = 0.0,
        initialMessages = example,
        chatTemplateOverride = ANDROID_TEXT_TEMPLATE,
        expectedRenderedPrompt = buildString {
            append("<bos><|turn>system\n").append(system.trim()).append("<turn|>\n")
            example.forEach { message ->
                append("<|turn>").append(if (message.role == GenUiPromptRole.USER) "user" else "model")
                    .append('\n').append(message.text.trim()).append("<turn|>\n")
            }
            append("<|turn>user\n").append((taskPrefix + response.trim()).trim())
                .append("<turn|>\n<|turn>model\n")
        },
    )

    companion object {
        // Android Contents serializes a text-only message as [{type:"text",text:...}].
        // The export template expects a string. This adapter changes representation only;
        // the native rendered bytes are checked against the original training template.
        private val ANDROID_TEXT_TEMPLATE = """
            {{- bos_token -}}
            {%- for message in messages -%}
            {%- set role = 'model' if message['role'] == 'assistant' else message['role'] -%}
            {{- '<|turn>' + role + '\n' -}}
            {%- if message['content'] is string -%}
            {{- message['content'] | trim -}}
            {%- else -%}
            {%- for part in message['content'] -%}
            {%- if part['type'] == 'text' -%}{{- part['text'] | trim -}}{%- endif -%}
            {%- endfor -%}
            {%- endif -%}
            {{- '<turn|>\n' -}}
            {%- endfor -%}
            {%- if add_generation_prompt -%}{{- '<|turn>model\n' -}}{%- endif -%}
        """.trimIndent()

        fun parse(json: String): TrainedPromptContract {
            // Pin the complete snapshot, including example and prefix. LF normalization only
            // accommodates Git's Windows line endings; JSON string content remains unchanged.
            require(sha256(json.replace("\r\n", "\n")) ==
                "96803a39869fb21f9f58a0f0adccab6f7746a32f124dc9da83d7df62a9f7ccb8") {
                "Trained E2B v10 prompt snapshot differs from the pinned checkpoint profile."
            }
            val root = JsonParser.parseString(json).asJsonObject
            require(root.get("schema_version").asInt == 1 &&
                root.get("version").asString == "a2ui_express_shared_prompt_v1" &&
                root.get("contract_sha256").asString == GenUiTrainedConverter.CONTRACT_SHA256 &&
                root.get("target_format").asString == "a2ui_express_v1" &&
                root.get("serialization_order").asString == "root-first") {
                "Unsupported trained prompt contract."
            }
            val scaffold = root.getAsJsonObject("scaffold")
            val messages = scaffold.getAsJsonArray("messages")
            require(messages.size() == 3 && messages.map { it.asJsonObject.get("role").asString } ==
                listOf("system", "user", "assistant")) { "Expected system and one worked example." }
            val content = messages.map { it.asJsonObject.get("content").asString }
            require(content.all(String::isNotBlank)) { "Empty trained prompt message." }
            require(sha256(content[0]) == root.get("system_prompt_sha256").asString) { "Trained system prompt checksum mismatch." }
            val prefix = scaffold.get("task_prefix").asString
            require(prefix.isNotBlank()) { "Empty trained task prefix." }
            return TrainedPromptContract(content[0], listOf(
                GenUiPromptMessage(GenUiPromptRole.USER, content[1]),
                GenUiPromptMessage(GenUiPromptRole.MODEL, content[2]),
            ), prefix)
        }

        private fun sha256(text: String): String = MessageDigest.getInstance("SHA-256")
            .digest(text.toByteArray(Charsets.UTF_8)).joinToString("") { "%02x".format(it) }
    }
}
